Sprint1
kan88/middle.messenger.praktikum.yandex pull request #1
Opened 2022-10-12 21:03 UTC by kan88

2022-10-13 06:37 UTC, podlovchenko requested changes
Привет, нет запуска сервера на express и попали папки dist и .parcel-cache в проект

2022-10-13 06:37 UTC, podlovchenko commented on .gitignore
> +.parcel-cache
Папка .parcel-cache попала в репозиторий

2022-10-13 06:37 UTC, podlovchenko commented on .gitignore
> +/dist
В проекте в некоторых файлах есть ошибка EOF
Для git важно наличие пустой строки в конце файла
https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log

2022-10-13 06:37 UTC, podlovchenko commented on .gitignore
> +/dist
И папка dist

2022-10-13 06:37 UTC, podlovchenko commented on package.json
> +    "start": "parcel serve src/index.hbs -p 3000 --open",
Команда start должна запускать сервер на express

2022-10-13 06:37 UTC, podlovchenko commented on package.json
> +    "parcel": "^2.7.0"
Лучше задавать фиксированные версии зависимостям. Если однажды решишь, удалить package-lock.json файл и попытаться повторно установить зависимости с помощью команды npm install, npm установит последние версии зависимостей, что может привести к ошибкам

2022-10-13 19:10 UTC, kan88 commented on .gitignore
> +/dist
Подскажи пожалуйста где можно посмотреть эти ошибки в моем проекте

2022-10-13 21:37 UTC, kan88 commented on .gitignore
> +.parcel-cache
не знаю почему не видит. Удалил вручную

2022-10-13 21:37 UTC, kan88 commented on package.json
> +    "start": "parcel serve src/index.hbs -p 3000 --open",
исправил

2022-10-13 21:37 UTC, kan88 commented on package.json
> +    "parcel": "^2.7.0"
есть

2022-10-14 13:24 UTC, podlovchenko commented
Привет, сейчас не настроена раздача статики
Локально страницы выглядит так
<img width="562" alt="Снимок экрана 2022-10-14 в 16 21 58" src="https://user-images.githubusercontent.com/22602747/195857830-9f18ef2a-caa4-4186-bd23-64b677d89772.png">
На нетлифае
<img width="958" alt="Снимок экрана 2022-10-14 в 16 22 12" src="https://user-images.githubusercontent.com/22602747/195857919-bf0629c4-4c99-4807-9fcd-e7ad4963cb3e.png">
При нажатии на ссылки регистрации `Cannot GET /reg.html`

2022-10-14 13:24 UTC, podlovchenko commented on index.js
> +app.listen(3000)
Часто требуется возможность получить порт снаружи скрипта, не изменяя код, это можно сделать через переменное окружение:
process.env.PORT || PORT;
https://nodejs.org/dist/latest-v8.x/docs/api/process.html

2022-10-15 17:20 UTC, podlovchenko commented
Добрый вечер, сейчас ошибка
`Error: ENOENT: no such file or directory, stat '/Users/podvb/kan88/middle.messenger.praktikum.yandex/dist/yandex-middle.html'`

2022-10-15 17:21 UTC, podlovchenko commented on src/index.js
> +app.get('/opensans.woff2', function (req, res) {
Достаточно 
`app.use(express.static(path.join(__dirname, "dist")));`

2022-10-15 20:50 UTC, kan88 commented on src/index.js
> +app.get('/opensans.woff2', function (req, res) {
вт это решило все мои проблемы, ранее я не знал как прописать роуты всем файлам потому что они делаются с хэшем. Теперь в сборке вернул хэш и теперь все работает как надо. спасибо

2022-10-16 11:32 UTC, podlovchenko commented on .gitignore
> +/dist
Перейти во вкладку files changed, там визуально видно

2022-10-16 11:33 UTC, podlovchenko commented on .gitignore
> +/dist
Для исправления можно использовать prettier (https://prettier.io/docs/en/install.html)

2022-10-16 11:33 UTC, podlovchenko commented
Работу принимаю)

2022-10-22 14:39 UTC, merged